#!/usr/bin/env node
// Share assets for OSCILLA: the inline favicon and apple-touch-icon in src/index.html, and the
// 1200x630 link-preview image published beside index.html by the Pages workflow.
//
//   npm run social            render site/og-image.png from dist/index.html and rewrite the
//                             social block in src/index.html (then run npm run build)
//   npm run social -- --icon-only  re-render only site/apple-touch-icon.png and the block
//   npm run social -- --check verify src/index.html carries the current block (no rendering)
//
// The preview is a screenshot of the real built app while it plays a tone, never a mock-up.
// The page does not load any of these files at runtime (project.single-file-deliverable).
//
// The touch icon is inlined into every page as a data: URL, so its screenshot is re-encoded as
// an indexed (palette) PNG by palettePng below: deterministic, plain zlib, well under half the
// size of the truecolour screenshot, with small per-channel errors on anti-aliased edges only.
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { createRequire } from 'node:module';
import path from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { deflateSync } from 'node:zlib';

const require = createRequire(import.meta.url);

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const SRC_HTML = path.join(ROOT, 'src', 'index.html');
const DIST_HTML = path.join(ROOT, 'dist', 'index.html');
const OG_IMAGE = path.join(ROOT, 'site', 'og-image.png');
const TOUCH_ICON = path.join(ROOT, 'site', 'apple-touch-icon.png');

export const SITE_URL = 'https://korczis.github.io/oscilla/';
export const OG_WIDTH = 1200;
export const OG_HEIGHT = 630;
const TITLE = 'OSCILLA · Interactive Sound & Frequency Lab';
const DESCRIPTION = 'A browser acoustic laboratory: generate tones, sweeps and sequences with '
  + 'the Web Audio API and see them as waveform, spectrum and spectrogram. Runs offline from '
  + 'one file.';
const IMAGE_ALT = 'The OSCILLA laboratory playing a tone, with its waveform, spectrum and '
  + 'transport controls.';
const BEGIN = '<!-- social:begin (generated by npm run social) -->';
const END = '<!-- social:end -->';

// The header's wave mark on the page background, as one self-contained SVG.
export const ICON_SVG = '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 50 50">'
  + '<defs><linearGradient id="g" x1="0" y1="0" x2="1" y2="0">'
  + '<stop offset="0" stop-color="#19b8f0"/><stop offset=".3" stop-color="#007afd"/>'
  + '<stop offset=".5" stop-color="#a164fa"/><stop offset=".72" stop-color="#f04ac4"/>'
  + '<stop offset="1" stop-color="#fcad38"/></linearGradient></defs>'
  + '<rect width="50" height="50" rx="11" fill="#020b15"/>'
  + '<path transform="translate(0 7)" d="M3 18h1.5c1.4 0 1.8-5 3.2-5s1.9 10 3.3 10 2-17 3.5-17 '
  + '2.1 25 3.6 25 2.1-31 3.6-31 2.1 27 3.6 27 2-19 3.4-19 1.9 11 3.3 11 1.6-5 3-5H47" '
  + 'fill="none" stroke="url(#g)" stroke-width="4.4" stroke-linecap="round" '
  + 'stroke-linejoin="round"/></svg>';

// ------------------------------------------------------------------------------- palette PNG
// An opaque screenshot re-encoded as an indexed PNG (colour type 3). Up to PALETTE_SIZE colours
// are chosen by median cut and refined by K_MEANS_ROUNDS of k-means over the distinct colours,
// each weighted by the square root of its pixel count, so the few anti-aliased edge colours keep
// entries of their own instead of being averaged into the background. Only integer histogram
// work, + - * /, Math.round and Math.sqrt in a fixed order: the same pixels give the same
// palette and indices on any machine. An image with at most PALETTE_SIZE colours is encoded
// losslessly, so re-encoding an encoded icon gives back the same pixels and palette.
const PALETTE_SIZE = 256;
const K_MEANS_ROUNDS = 20;
const CHANNELS = [16, 8, 0]; // bit offsets of R, G, B in a packed 0xRRGGBB colour
const channel = (rgb, shift) => (rgb >> shift) & 255;

function distance2(a, b) {
  let d = 0;
  for (const s of CHANNELS) d += (channel(a, s) - channel(b, s)) ** 2;
  return d;
}

/** Palette (packed RGB) for the distinct colours of `colors` ({ rgb, weight }[], sorted). */
function choosePalette(colors, size) {
  const weightOf = (box) => box.reduce((a, c) => a + c.weight, 0);
  const span = (box, s) => {
    let lo = 255;
    let hi = 0;
    for (const c of box) {
      lo = Math.min(lo, channel(c.rgb, s));
      hi = Math.max(hi, channel(c.rgb, s));
    }
    return hi - lo;
  };
  // Median cut: split the box with the widest weighted channel span at its weighted median.
  const boxes = [colors];
  while (boxes.length < size) {
    let best = -1;
    let bestScore = 0;
    let bestShift = 16;
    boxes.forEach((box, i) => {
      if (box.length < 2) return;
      const w = Math.sqrt(weightOf(box));
      for (const s of CHANNELS) {
        const score = span(box, s) * w;
        if (score > bestScore) [best, bestScore, bestShift] = [i, score, s];
      }
    });
    if (best < 0) break;
    const box = [...boxes[best]].sort((a, b) => (
      channel(a.rgb, bestShift) - channel(b.rgb, bestShift) || a.rgb - b.rgb));
    const half = weightOf(box) / 2;
    let acc = 0;
    let cut = box.length - 1;
    for (let i = 0; i < box.length - 1; i++) {
      acc += box[i].weight;
      if (acc >= half) {
        cut = i + 1;
        break;
      }
    }
    boxes.splice(best, 1, box.slice(0, cut), box.slice(cut));
  }
  const mean = (members, fallback) => {
    const sum = [0, 0, 0];
    let w = 0;
    for (const c of members) {
      CHANNELS.forEach((s, k) => { sum[k] += channel(c.rgb, s) * c.weight; });
      w += c.weight;
    }
    if (!w) return fallback;
    return sum.reduce((rgb, v, k) => rgb | (Math.round(v / w) << CHANNELS[k]), 0);
  };
  let palette = boxes.map((box) => mean(box, 0));
  for (let round = 0; round < K_MEANS_ROUNDS; round++) {
    const members = palette.map(() => []);
    for (const c of colors) members[nearest(palette, c.rgb)].push(c);
    palette = palette.map((p, i) => mean(members[i], p));
  }
  return palette;
}

function nearest(palette, rgb) {
  let best = 0;
  let bestD = Infinity;
  for (let i = 0; i < palette.length; i++) {
    const d = distance2(palette[i], rgb);
    if (d < bestD) [best, bestD] = [i, d];
  }
  return best;
}

const CRC_TABLE = Array.from({ length: 256 }, (_, n) => {
  let c = n;
  for (let k = 0; k < 8; k++) c = c & 1 ? 0xedb88320 ^ (c >>> 1) : c >>> 1;
  return c >>> 0;
});

function crc32(buf) {
  let c = 0xffffffff;
  for (const byte of buf) c = CRC_TABLE[(c ^ byte) & 255] ^ (c >>> 8);
  return (c ^ 0xffffffff) >>> 0;
}

function pngChunk(type, data) {
  const head = Buffer.alloc(8);
  head.writeUInt32BE(data.length, 0);
  head.write(type, 4, 'ascii');
  const crc = Buffer.alloc(4);
  crc.writeUInt32BE(crc32(Buffer.concat([head.subarray(4), data])), 0);
  return Buffer.concat([head, data, crc]);
}

/**
 * Re-encode an opaque PNG as an indexed PNG (see above). Palette entries are ordered by pixel
 * count (then colour), the smallest bit depth that holds them is used, rows are unfiltered
 * (the best choice for indices) and IDAT is deflated at level 9.
 * @param {Buffer} png  any PNG pngjs can read; every pixel must be opaque
 * @returns {Buffer}
 */
export function palettePng(png) {
  const { PNG } = require('pngjs');
  const { width, height, data } = PNG.sync.read(png);
  const pixels = new Uint32Array(width * height);
  const counts = new Map();
  for (let i = 0; i < pixels.length; i++) {
    if (data[i * 4 + 3] !== 255) throw new Error('palettePng: the image must be opaque');
    const rgb = (data[i * 4] << 16) | (data[i * 4 + 1] << 8) | data[i * 4 + 2];
    pixels[i] = rgb;
    counts.set(rgb, (counts.get(rgb) || 0) + 1);
  }
  const colors = [...counts].sort((a, b) => a[0] - b[0])
    .map(([rgb, n]) => ({ rgb, weight: Math.sqrt(n) }));
  const chosen = choosePalette(colors, PALETTE_SIZE);
  const slot = new Map(colors.map((c) => [c.rgb, nearest(chosen, c.rgb)]));
  // Keep the entries in use, most frequent first, so equal pixels give equal files.
  const used = new Map();
  for (const rgb of pixels) {
    const p = chosen[slot.get(rgb)];
    used.set(p, (used.get(p) || 0) + 1);
  }
  const palette = [...used].sort((a, b) => b[1] - a[1] || a[0] - b[0]).map(([p]) => p);
  const index = new Map(palette.map((p, i) => [p, i]));
  const depth = [1, 2, 4, 8].find((d) => palette.length <= 2 ** d);
  const rowBytes = Math.ceil((width * depth) / 8);
  const raw = Buffer.alloc((rowBytes + 1) * height); // filter byte 0 (None) per row
  for (let y = 0; y < height; y++) {
    for (let x = 0; x < width; x++) {
      const v = index.get(chosen[slot.get(pixels[y * width + x])]);
      const bit = x * depth;
      raw[y * (rowBytes + 1) + 1 + (bit >> 3)] |= v << (8 - depth - (bit & 7));
    }
  }
  const ihdr = Buffer.alloc(13);
  ihdr.writeUInt32BE(width, 0);
  ihdr.writeUInt32BE(height, 4);
  // Bit depth, colour type 3 (indexed), deflate, adaptive filtering, no interlace.
  ihdr.set([depth, 3, 0, 0, 0], 8);
  const plte = Buffer.alloc(palette.length * 3);
  palette.forEach((p, i) => plte.set(CHANNELS.map((s) => channel(p, s)), i * 3));
  return Buffer.concat([
    Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a]),
    pngChunk('IHDR', ihdr),
    pngChunk('PLTE', plte),
    pngChunk('IDAT', deflateSync(raw, { level: 9, memLevel: 9 })),
    pngChunk('IEND', Buffer.alloc(0)),
  ]);
}

const esc =(s) => s.replace(/&/g, '&amp;').replace(/"/g, '&quot;').replace(/</g, '&lt;');

export function socialBlock(touchIconPng) {
  const icon = `data:image/svg+xml,${encodeURIComponent(ICON_SVG)}`;
  const touch = `data:image/png;base64,${touchIconPng.toString('base64')}`;
  const image = `${SITE_URL}og-image.png`;
  return [
    BEGIN,
    `<link rel="icon" type="image/svg+xml" href="${icon}">`,
    `<link rel="apple-touch-icon" sizes="180x180" href="${touch}">`,
    '<meta name="theme-color" content="#020b15" media="(prefers-color-scheme: dark)">',
    '<meta name="theme-color" content="#e9eef4" media="(prefers-color-scheme: light)">',
    '<meta property="og:type" content="website">',
    '<meta property="og:site_name" content="OSCILLA">',
    `<meta property="og:title" content="${esc(TITLE)}">`,
    `<meta property="og:description" content="${esc(DESCRIPTION)}">`,
    `<meta property="og:url" content="${SITE_URL}">`,
    '<meta property="og:locale" content="en_US">',
    `<meta property="og:image" content="${image}">`,
    '<meta property="og:image:type" content="image/png">',
    `<meta property="og:image:width" content="${OG_WIDTH}">`,
    `<meta property="og:image:height" content="${OG_HEIGHT}">`,
    `<meta property="og:image:alt" content="${esc(IMAGE_ALT)}">`,
    '<meta name="twitter:card" content="summary_large_image">',
    `<meta name="twitter:title" content="${esc(TITLE)}">`,
    `<meta name="twitter:description" content="${esc(DESCRIPTION)}">`,
    `<meta name="twitter:image" content="${image}">`,
    `<meta name="twitter:image:alt" content="${esc(IMAGE_ALT)}">`,
    END,
  ].map((l, i) => (i === 0 ? l : `  ${l}`)).join('\n');
}

function writeBlock(block) {
  const html = readFileSync(SRC_HTML, 'utf8');
  const start = html.indexOf(BEGIN);
  const stop = html.indexOf(END);
  let next;
  if (start >= 0 && stop > start) {
    next = html.slice(0, start) + block + html.slice(stop + END.length);
  } else {
    next = html.replace('  <!-- @inline-css -->', `  ${block}\n  <!-- @inline-css -->`);
  }
  writeFileSync(SRC_HTML, next);
}

async function render({ iconOnly = false } = {}) {
  const { chromium } = await import('playwright');
  const browser = await chromium.launch({ args: ['--autoplay-policy=no-user-gesture-required'] });
  try {
    const iconPage = await browser.newPage({ viewport: { width: 180, height: 180 } });
    await iconPage.setContent(`<style>html,body{margin:0;background:#020b15}svg{display:block;
      width:180px;height:180px}</style>${ICON_SVG}`);
    const touch = palettePng(await iconPage.screenshot({ type: 'png' }));
    writeFileSync(TOUCH_ICON, touch);
    if (iconOnly) return touch;

    // 1536 x 806 at 0.78125 device pixels per CSS pixel is exactly 1200 x 630.
    const scale = OG_WIDTH / 1536;
    const page = await browser.newPage({
      viewport: { width: 1536, height: Math.round(OG_HEIGHT / scale) },
      deviceScaleFactor: scale,
      colorScheme: 'dark',
    });
    await page.goto(pathToFileURL(DIST_HTML).href);
    await page.waitForSelector('html[data-ready="true"]', { timeout: 15000 });
    // Hold the main HOLD TO PLAY button, as a person would, so the views show a live tone.
    const hold = await page.locator('#osc-hold-play').boundingBox();
    await page.mouse.move(hold.x + hold.width / 2, hold.y + hold.height / 2);
    await page.mouse.down();
    await page.waitForTimeout(1200);
    await page.mouse.move(0, 0);
    const shot = await page.screenshot({ type: 'png' });
    await page.mouse.up();
    writeFileSync(OG_IMAGE, shot);
    return touch;
  } finally {
    await browser.close();
  }
}

async function main() {
  mkdirSync(path.dirname(OG_IMAGE), { recursive: true });
  if (process.argv.includes('--check')) {
    const html = readFileSync(SRC_HTML, 'utf8');
    const touch = readFileSync(TOUCH_ICON);
    if (!html.includes(socialBlock(touch))) {
      console.error('social: src/index.html is out of date; run npm run social');
      process.exit(1);
    }
    console.log('social: src/index.html carries the current block');
    return;
  }
  const iconOnly = process.argv.includes('--icon-only');
  const touch = await render({ iconOnly });
  writeBlock(socialBlock(touch));
  const wrote = iconOnly ? [TOUCH_ICON] : [OG_IMAGE, TOUCH_ICON];
  console.log(`social: wrote ${wrote.map((f) => path.relative(ROOT, f)).join(', ')}`
    + ' and the src/index.html block; run npm run build');
}

if (import.meta.url === pathToFileURL(process.argv[1]).href) await main();
