#!/usr/bin/env node
// Share assets for OSCILLA: the inline favicon and apple-touch-icon in src/index.html, and the
// 1200x630 link-preview image published beside index.html by the Pages workflow.
//
//   npm run social            render site/og-image.png from dist/index.html and rewrite the
//                             social block in src/index.html (then run npm run build)
//   npm run social -- --check verify src/index.html carries the current block (no rendering)
//
// The preview is a screenshot of the real built app while it plays a tone, never a mock-up.
// The page does not load any of these files at runtime (project.single-file-deliverable).
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const SRC_HTML = path.join(ROOT, 'src', 'index.html');
const DIST_HTML = path.join(ROOT, 'dist', 'index.html');
const OG_IMAGE = path.join(ROOT, 'site', 'og-image.png');
const TOUCH_ICON = path.join(ROOT, 'site', 'apple-touch-icon.png');

export const SITE_URL = 'https://korczis.github.io/oscilla/';
export const OG_WIDTH = 1200;
export const OG_HEIGHT = 630;
const TITLE = 'OSCILLA · Interactive Sound & Frequency Lab';
const DESCRIPTION = 'A browser acoustic laboratory: generate tones, sweeps and sequences with '
  + 'the Web Audio API and see them as waveform, spectrum and spectrogram. Runs offline from '
  + 'one file.';
const IMAGE_ALT = 'The OSCILLA laboratory playing a tone, with its waveform, spectrum and '
  + 'transport controls.';
const BEGIN = '<!-- social:begin (generated by npm run social) -->';
const END = '<!-- social:end -->';

// The header's wave mark on the page background, as one self-contained SVG.
export const ICON_SVG = '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 50 50">'
  + '<defs><linearGradient id="g" x1="0" y1="0" x2="1" y2="0">'
  + '<stop offset="0" stop-color="#19b8f0"/><stop offset=".3" stop-color="#007afd"/>'
  + '<stop offset=".5" stop-color="#a164fa"/><stop offset=".72" stop-color="#f04ac4"/>'
  + '<stop offset="1" stop-color="#fcad38"/></linearGradient></defs>'
  + '<rect width="50" height="50" rx="11" fill="#020b15"/>'
  + '<path transform="translate(0 7)" d="M3 18h1.5c1.4 0 1.8-5 3.2-5s1.9 10 3.3 10 2-17 3.5-17 '
  + '2.1 25 3.6 25 2.1-31 3.6-31 2.1 27 3.6 27 2-19 3.4-19 1.9 11 3.3 11 1.6-5 3-5H47" '
  + 'fill="none" stroke="url(#g)" stroke-width="4.4" stroke-linecap="round" '
  + 'stroke-linejoin="round"/></svg>';

const esc = (s) => s.replace(/&/g, '&amp;').replace(/"/g, '&quot;').replace(/</g, '&lt;');

export function socialBlock(touchIconPng) {
  const icon = `data:image/svg+xml,${encodeURIComponent(ICON_SVG)}`;
  const touch = `data:image/png;base64,${touchIconPng.toString('base64')}`;
  const image = `${SITE_URL}og-image.png`;
  return [
    BEGIN,
    `<link rel="icon" type="image/svg+xml" href="${icon}">`,
    `<link rel="apple-touch-icon" sizes="180x180" href="${touch}">`,
    '<meta name="theme-color" content="#020b15" media="(prefers-color-scheme: dark)">',
    '<meta name="theme-color" content="#e9eef4" media="(prefers-color-scheme: light)">',
    '<meta property="og:type" content="website">',
    '<meta property="og:site_name" content="OSCILLA">',
    `<meta property="og:title" content="${esc(TITLE)}">`,
    `<meta property="og:description" content="${esc(DESCRIPTION)}">`,
    `<meta property="og:url" content="${SITE_URL}">`,
    '<meta property="og:locale" content="en_US">',
    `<meta property="og:image" content="${image}">`,
    '<meta property="og:image:type" content="image/png">',
    `<meta property="og:image:width" content="${OG_WIDTH}">`,
    `<meta property="og:image:height" content="${OG_HEIGHT}">`,
    `<meta property="og:image:alt" content="${esc(IMAGE_ALT)}">`,
    '<meta name="twitter:card" content="summary_large_image">',
    `<meta name="twitter:title" content="${esc(TITLE)}">`,
    `<meta name="twitter:description" content="${esc(DESCRIPTION)}">`,
    `<meta name="twitter:image" content="${image}">`,
    `<meta name="twitter:image:alt" content="${esc(IMAGE_ALT)}">`,
    END,
  ].map((l, i) => (i === 0 ? l : `  ${l}`)).join('\n');
}

function writeBlock(block) {
  const html = readFileSync(SRC_HTML, 'utf8');
  const start = html.indexOf(BEGIN);
  const stop = html.indexOf(END);
  let next;
  if (start >= 0 && stop > start) {
    next = html.slice(0, start) + block + html.slice(stop + END.length);
  } else {
    next = html.replace('  <!-- @inline-css -->', `  ${block}\n  <!-- @inline-css -->`);
  }
  writeFileSync(SRC_HTML, next);
}

async function render() {
  const { chromium } = await import('playwright');
  const browser = await chromium.launch({ args: ['--autoplay-policy=no-user-gesture-required'] });
  try {
    const iconPage = await browser.newPage({ viewport: { width: 180, height: 180 } });
    await iconPage.setContent(`<style>html,body{margin:0;background:#020b15}svg{display:block;
      width:180px;height:180px}</style>${ICON_SVG}`);
    const touch = await iconPage.screenshot({ type: 'png' });
    writeFileSync(TOUCH_ICON, touch);

    // 1536 x 806 at 0.78125 device pixels per CSS pixel is exactly 1200 x 630.
    const scale = OG_WIDTH / 1536;
    const page = await browser.newPage({
      viewport: { width: 1536, height: Math.round(OG_HEIGHT / scale) },
      deviceScaleFactor: scale,
      colorScheme: 'dark',
    });
    await page.goto(pathToFileURL(DIST_HTML).href);
    await page.waitForSelector('html[data-ready="true"]', { timeout: 15000 });
    // Hold the main HOLD TO PLAY button, as a person would, so the views show a live tone.
    const hold = await page.locator('#osc-hold-play').boundingBox();
    await page.mouse.move(hold.x + hold.width / 2, hold.y + hold.height / 2);
    await page.mouse.down();
    await page.waitForTimeout(1200);
    await page.mouse.move(0, 0);
    const shot = await page.screenshot({ type: 'png' });
    await page.mouse.up();
    writeFileSync(OG_IMAGE, shot);
    return touch;
  } finally {
    await browser.close();
  }
}

async function main() {
  mkdirSync(path.dirname(OG_IMAGE), { recursive: true });
  if (process.argv.includes('--check')) {
    const html = readFileSync(SRC_HTML, 'utf8');
    const touch = readFileSync(TOUCH_ICON);
    if (!html.includes(socialBlock(touch))) {
      console.error('social: src/index.html is out of date; run npm run social');
      process.exit(1);
    }
    console.log('social: src/index.html carries the current block');
    return;
  }
  const touch = await render();
  writeBlock(socialBlock(touch));
  console.log(`social: wrote ${path.relative(ROOT, OG_IMAGE)}, ${path.relative(ROOT, TOUCH_ICON)}`
    + ' and the src/index.html block; run npm run build');
}

if (import.meta.url === pathToFileURL(process.argv[1]).href) await main();
